package band

// StockCatalog is the global advisory stock catalog containing mock metadata and fundamentals
var StockCatalog = map[string]StockContext{
	"NVDA": {
		Ticker:         "NVDA",
		CompanyName:    "NVIDIA Corp.",
		Sector:         "Technology",
		Industry:       "Semiconductors",
		MarketCap:      "3.15 Trillion",
		CurrentPrice:   128.50,
		DailyChange:    5.20,
		DailyChangePct: 4.21,
		Volume:         "45.2 Million",
		FiftyTwoWHigh:  140.76,
		FiftyTwoWLow:   39.23,
		PERatio:        72.5,
		EPS:            1.77,
		Revenue:        "26.04 Billion",
		DebtRatio:      0.18,
		AIScore:        92,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/nvidia.com",
		Overview:       "NVIDIA Corporation designs graphics processing units (GPUs) for the gaming and professional markets, as well as system on a chip units (SoCs) for the mobile computing and automotive market. NVIDIA has expanded its focus to artificial intelligence, cloud computing, and automated driving.",
	},
	"AAPL": {
		Ticker:         "AAPL",
		CompanyName:    "Apple Inc.",
		Sector:         "Technology",
		Industry:       "Consumer Electronics",
		MarketCap:      "2.85 Trillion",
		CurrentPrice:   178.45,
		DailyChange:    2.03,
		DailyChangePct: 1.15,
		Volume:         "52.1 Million",
		FiftyTwoWHigh:  199.62,
		FiftyTwoWLow:   164.08,
		PERatio:        28.4,
		EPS:            6.43,
		Revenue:        "90.75 Billion",
		DebtRatio:      1.45,
		AIScore:        82,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/apple.com",
		Overview:       "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company is best known for its hardware products, including the iPhone, iPad, Mac, Apple Watch, and services including Apple Music, iCloud, and Apple Pay.",
	},
	"TSLA": {
		Ticker:         "TSLA",
		CompanyName:    "Tesla Inc.",
		Sector:         "Consumer Cyclical",
		Industry:       "Auto Manufacturers",
		MarketCap:      "670.4 Billion",
		CurrentPrice:   210.80,
		DailyChange:    -5.18,
		DailyChangePct: -2.40,
		Volume:         "88.4 Million",
		FiftyTwoWHigh:  299.29,
		FiftyTwoWLow:   138.80,
		PERatio:        61.2,
		EPS:            3.44,
		Revenue:        "21.30 Billion",
		DebtRatio:      0.08,
		AIScore:        64,
		Recommendation: "HOLD",
		Logo:           "https://logo.clearbit.com/tesla.com",
		Overview:       "Tesla, Inc. designs, develops, manufactures, sells, and leases fully electric vehicles, energy generation and storage systems, and offers services related to its products. The company is a pioneer in sustainable transport, automated driving software, and commercial scale energy grids.",
	},
	"MSFT": {
		Ticker:         "MSFT",
		CompanyName:    "Microsoft Corp.",
		Sector:         "Technology",
		Industry:       "Infrastructure Software",
		MarketCap:      "3.10 Trillion",
		CurrentPrice:   415.50,
		DailyChange:    3.50,
		DailyChangePct: 0.85,
		Volume:         "22.8 Million",
		FiftyTwoWHigh:  430.82,
		FiftyTwoWLow:   315.18,
		PERatio:        36.2,
		EPS:            11.06,
		Revenue:        "61.86 Billion",
		DebtRatio:      0.28,
		AIScore:        88,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/microsoft.com",
		Overview:       "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment includes Office, Exchange, SharePoint, Microsoft Teams, Skype, and LinkedIn. It is a major leader in cloud computing via Microsoft Azure and AI tools.",
	},
	"AMD": {
		Ticker:         "AMD",
		CompanyName:    "Advanced Micro Devices",
		Sector:         "Technology",
		Industry:       "Semiconductors",
		MarketCap:      "262.1 Billion",
		CurrentPrice:   162.30,
		DailyChange:    -3.23,
		DailyChangePct: -1.95,
		Volume:         "48.5 Million",
		FiftyTwoWHigh:  227.30,
		FiftyTwoWLow:   93.12,
		PERatio:        330.0,
		EPS:            0.49,
		Revenue:        "5.47 Billion",
		DebtRatio:      0.03,
		AIScore:        71,
		Recommendation: "HOLD",
		Logo:           "https://logo.clearbit.com/amd.com",
		Overview:       "Advanced Micro Devices, Inc. operates as a semiconductor company worldwide. It operates in two segments, Computing and Graphics; and Enterprise, Embedded, and Semi-Custom. The company offers x86 microprocessors, chipsets, discrete and integrated graphics processing units, and AI compute chips.",
	},
	"AMZN": {
		Ticker:         "AMZN",
		CompanyName:    "Amazon.com Inc.",
		Sector:         "Consumer Cyclical",
		Industry:       "Internet Retail",
		MarketCap:      "1.87 Trillion",
		CurrentPrice:   180.15,
		DailyChange:    1.55,
		DailyChangePct: 0.87,
		Volume:         "35.1 Million",
		FiftyTwoWHigh:  191.70,
		FiftyTwoWLow:   118.35,
		PERatio:        41.5,
		EPS:            4.34,
		Revenue:        "143.31 Billion",
		DebtRatio:      0.38,
		AIScore:        85,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/amazon.com",
		Overview:       "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. It operates through three segments: North America, International, and Amazon Web Services (AWS). AWS provides secure cloud hosting and infrastructure solutions worldwide.",
	},
	"GOOGL": {
		Ticker:         "GOOGL",
		CompanyName:    "Alphabet Inc.",
		Sector:         "Technology",
		Industry:       "Internet Content & Information",
		MarketCap:      "2.18 Trillion",
		CurrentPrice:   175.40,
		DailyChange:    2.10,
		DailyChangePct: 1.21,
		Volume:         "28.2 Million",
		FiftyTwoWHigh:  189.38,
		FiftyTwoWLow:   115.35,
		PERatio:        26.8,
		EPS:            6.54,
		Revenue:        "80.54 Billion",
		DebtRatio:      0.06,
		AIScore:        86,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/google.com",
		Overview:       "Alphabet Inc. offers various platforms and services in the United States, Europe, the Americas, and the Asia-Pacific. It operates through Google Services, Google Cloud, and Other Bets segments. It is famous for its search engine Google, YouTube platform, Android OS, and Gemini AI systems.",
	},
	"META": {
		Ticker:         "META",
		CompanyName:    "Meta Platforms Inc.",
		Sector:         "Technology",
		Industry:       "Internet Content & Information",
		MarketCap:      "1.25 Trillion",
		CurrentPrice:   495.20,
		DailyChange:    -4.80,
		DailyChangePct: -0.96,
		Volume:         "18.4 Million",
		FiftyTwoWHigh:  531.49,
		FiftyTwoWLow:   260.00,
		PERatio:        27.5,
		EPS:            18.00,
		Revenue:        "36.45 Billion",
		DebtRatio:      0.12,
		AIScore:        89,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/meta.com",
		Overview:       "Meta Platforms, Inc. focuses on building products that enable people to connect and share through mobile devices, personal computers, virtual reality headsets, and wearables. It operates in two segments: Family of Apps (Facebook, Instagram, Messenger, WhatsApp) and Reality Labs (VR/AR hardware).",
	},
	"NFLX": {
		Ticker:         "NFLX",
		CompanyName:    "Netflix Inc.",
		Sector:         "Communication Services",
		Industry:       "Entertainment",
		MarketCap:      "268.4 Billion",
		CurrentPrice:   620.30,
		DailyChange:    8.45,
		DailyChangePct: 1.38,
		Volume:         "3.5 Million",
		FiftyTwoWHigh:  639.00,
		FiftyTwoWLow:   382.00,
		PERatio:        43.2,
		EPS:            14.35,
		Revenue:        "9.37 Billion",
		DebtRatio:      0.65,
		AIScore:        80,
		Recommendation: "BUY",
		Logo:           "https://logo.clearbit.com/netflix.com",
		Overview:       "Netflix, Inc. provides entertainment services with paid memberships in approximately 190 countries. It offers TV series, documentaries, feature films, and mobile games across various genres and languages. It allows members to watch content through internet-connected screens.",
	},
}
