CREATE TABLE IF NOT EXISTS stock_logos (
    symbol VARCHAR(50) PRIMARY KEY,
    company_name VARCHAR(255),
    logo_url TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
